# Generated by Django 4.1.1 on 2023-01-31 01:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("pic", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "flavor",
                    models.CharField(
                        choices=[
                            ("Cheese", "Cheese"),
                            ("Pepperoni", "Pepperoni"),
                            ("Custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "extras",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Extra Cheese", "Extra Cheese"),
                            ("Pepperoni", "Pepperoni"),
                            ("Bacon", "Bacon"),
                            ("Peppers", "Peppers"),
                            ("Mushrooms", "Mushrooms"),
                            ("Chicken", "Chicken"),
                            ("Pesto", "Pesto"),
                            ("Ranch", "Ranch"),
                            ("Beef", "Beef"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
