# Generated by Django 4.1.1 on 2023-02-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0003_alter_pizza_extras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                max_length=32,
            ),
        ),
    ]
