# Generated by Django 4.1.1 on 2023-02-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0006_remove_pizza_flavor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("pic", models.ImageField(upload_to="")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IceCream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("pic", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                (
                    "flavor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Vanilla", "Vanilla"),
                            ("Chocolate", "Chocolate"),
                            ("Strawberry", "Strawberry"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
