# Generated by Django 4.1.1 on 2023-02-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0007_cookie_icecream"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("pic", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("Individual", "Individual"), ("2L", "2L")],
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
