# Generated by Django 4.1.1 on 2023-02-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0009_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField()),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                            ("Individual", "Individual"),
                            ("2L", "2L"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
