# Generated by Django 4.1.1 on 2023-02-23 23:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0010_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="size",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Small", "Small"),
                    ("Medium", "Medium"),
                    ("Large", "Large"),
                    ("Individual", "Individual"),
                    ("2L", "2L"),
                ],
                max_length=32,
            ),
        ),
    ]
