# Generated by Django 4.1.1 on 2023-02-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0011_alter_menuitem_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Small", "Small"),
                    ("Medium", "Medium"),
                    ("Large", "Large"),
                    ("Individual", "Individual"),
                    ("2L", "2L"),
                ],
                max_length=16,
            ),
        ),
    ]
