# Generated by Django 4.1.1 on 2023-02-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0012_alter_menuitem_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="size",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
