# Generated by Django 4.1.1 on 2023-02-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0013_alter_menuitem_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
